- name: check for existence
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: join cluster
  block:
    - name: retrieve kube join command
      shell: "kubeadm token create --print-join-command"
      delegate_to: "{{ groups['masters'][0] }}"
      register: results

    #- name: debug
    #  debug:
    #    msg: "{{ results }}"

    - name: get arg list
      set_fact:
        join_list: "{{ results.stdout.split() }}"

    - name: create join configuration
      template:
        src: kubeadm.conf.j2
        dest: "/home/ubuntu/kubeadm.conf"
        mode: 0644
      vars:
        hostname: "{{ private_dns }}"
        publicname: "{{ inventory_hostname }}"
        endpoint: "{{ join_list[2] }}"
        token: "{{ join_list[4] }}"
        hash: "{{ join_list[6] }}"

    - name: kubeadm join
      shell: "kubeadm join --config /home/ubuntu/kubeadm.conf"
      ignore_errors : true
  when: kubelet_conf.stat.exists == false
