- name: common tasks for all hosts
  hosts: all # normally all
  become: yes
  roles:
    - common

#- name: wait
#  hosts: all
#  tasks:
#    - name: Wait for the reboot and reconnect
#      wait_for:
#        port: 22
#        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
#        search_regex: OpenSSH
#        delay: 10
#        timeout: 60
#      connection: local
#
#    - name: Check the Uptime of the servers
#      shell: "uptime"
#      register: Uptime
#
#    - debug: var=Uptime

- name: setup master
  hosts: masters
  become: yes
  roles:
    - pre_kubernetes
    - node_exporter
    - master
#    - cadvisor

- name: setup workers
  hosts: workers
  become: yes
  roles:
    - node_exporter
    - worker

- name: reboot all
  hosts: all
  become: yes
  roles:
    - restart


#    - cadvisor

#- name: post setup
#  hosts: masters
#  roles:
#    - post
