- name: "create group {{ account_name }}"
  group:
    name: "{{ account_name }}"
    gid: "{{group_id }}"
    state: present

- name: "create user {{ account_name }}"
  user:
    name: "{{  account_name }}"
    create_home: false
    shell: /bin/false
    group: "{{ account_name }}"
    uid: "{{ user_id }}"
    state: present
