- name: copy kubeadm config file
  template:
    src: kubeadm.conf.j2.aws
    dest: /tmp/kubeadm.conf
    mode: 0666
    owner: ubuntu
    group: ubuntu
  vars:
    hostname: "{{ private_dns }}"
    privateip: "{{ ansible_default_ipv4.address }}"
    publicname: "{{ inventory_hostname }}"

- name: create etcd data directory
  file:
    state: directory
    path: /var/lib/etcd
    owner: etcd
    group: etcd
    mode: 0700

- name: check for existence
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: create certificates for kubernetes
  shell: "kubeadm init phase certs all --config /tmp/kubeadm.conf"
  when: kubelet_conf.stat.exists == false

- name: set ownership for etcd certs
  file:
    owner: etcd
    group: etcd
    path: /etc/kubernetes/pki/etcd
    recurse: true

- name: start kubeadm
  shell: "kubeadm init --skip-phases certs --config /tmp/kubeadm.conf"
  when: kubelet_conf.stat.exists == false

- name: create .kube directory
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: copy config file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    owner: ubuntu
    group: ubuntu
    mode: 0400
    remote_src: yes

# setup flannel
- name: download flannel yaml
  get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: /tmp/kube-flannel.yml
    mode: 0644

- name: apply flannel yaml
  shell: kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f /tmp/kube-flannel.yml
