apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    serviceTier: test
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: default
  labels:
    serviceTier: test
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Local
